---
title: "한드판 케빈 베이컨 놀이 - 시각화"
# author: "Kyungmin Lee"
date: Dec 14, 2017
output: html_notebook
---

## 시각화 1
```{r, message=FALSE}
rm(list=ls())
# 패키지 불러오기
library(network)
library(sna)
library(GGally)
library(scales)
```

```{r}
## Rdata 불러오기
list.files(pattern = 'RData')
load('sixDegreesOfKdrData2.RData')
```

```{r}
# 네트워크 맵에 사용될 각종 인자값 설정
# - 노드의 컬러: 중개중심성 상위 2%에 금색(gold) 지정, 나머지는 밝은회색(gray80)으로
# - 노드의 크기: 연결중심성에 비례하여 설정
# - 엣지(연결선)의 두께: 함께 출연한 횟수로
```

```{r}
# 중개중심성 상위 2%인 기준 확인
quant98 <- quantile(x = btwn_centrl, probs = 0.98)
quant98 # 56429.41 보다 크면 상위 2% 인듯
```

```{r}
# 중개중심성 상위 2%인 배우들에게 'Star' 지정 
# %v% : network library에서 network 객체에 쓰는 operator
net_actors %v% 'color' <- ifelse(btwn_centrl > quant98, 'Star', 'Normal')
```

```{r}
# 'Star'가 할당된 배우의 수 확인
table(net_actors %v% 'color') # Normal: 5270   Star: 108
```

```{r}
# 중개중심성이 상위 2%인 배우의 노드에 금색(gold) 할당
node_colors <- c('Star' = 'gold',
                 'Normal' = 'gray80')
node_colors
```

```{r}
# 엣지의 두께 설정
# 상관관계 행렬이 있으면 상관계수로 설정할 수 있으나 이번 예제에서는 배우 간 행렬을 이용함 
set.edge.value(x = net_actors,
               attrname = 'edge_size',
               value = actor_mul * 0.1) # ??어떤 계산인지 좀 더 보기??
```

```{r}
# 네트워크 맵 그리기
ggnet2(
    # 네트워크 객체 할당 
    net = net_actors,
    # 겹치는 노드를 흩어지게 처리
    layout.par = list(cell.jitter = 0.8),
    
    # 노드에 레이블 출력 여부 설정
    label = TRUE,
    # 레이블의 폰트 사이즈 설정
    label.size = 3,
    # 레이블의 컬러 설정
    label.color = 'gray30',
    
    # 노드의 색상을 구분하는 기준. 위에서 만든 'color'를 사용
    # 'color' 대신에 'white'처럼 전체 노드에 대해 하나의 색상으로 지정 가능
    node.color = 'color',
    # 노드의 색상 팔레트
    palette = node_colors,
    
    # 노드의 크기를 연결중심성(degree centrality)에 비례하도록 설정
    node.size = 'degree_centrl', # 그냥 이렇게만 쓰면???
    # 엣지의 두께는 함께 출연한 횟수에 비례하도록 설정 
    edge.size = 'edge_size',
    
    # 범례 위치 지정. 이번 예제에서는 범례를 출력하지 않도록 설정
    legend.position = 'None',
    # 네트워크 모양 설정 
    # 'circle','kamadakawai','fruchtermanreingold','circrand'
    mode = 'fruchtermanreingold',
    # 글자 폰트 지정
    family = 'NanumGothic')
```
#### 짠! 전혀 알아볼 수 없다... gold는 보이지도 않음.. 
배우를 몇 명만 뽑아보기로..

```{r}
## 특정 인물들을 중심으로 네트워크 맵 그리기
# 중개중심성 상위 3명에 대해서 네트워크 맵 그리기
key_actors <- c('김종호', '민준현', '안내상')
```

```{r}
# 상위 3명에 대해 배우 간 행렬을 아래와 같이 변형함
# 배우 간 행렬에서 상위 3명의 열(컬럼)만 남기고, 행에서는 상위 3명을 제거
key_actors_mul <- actor_mul[ , key_actors]
key_actors_mul <- key_actors_mul[!rownames(key_actors_mul) %in% key_actors, ]
```

```{r}
# 행의 합이 0 초과인 값만 남기기
# 즉, 상위 3명과 함께 영화에 출연한 적이 있는 배우들만 남기기
key_actors_mul <- key_actors_mul[rowSums(key_actors_mul) > 0,]
```

```{r}
class(key_actors_mul) # matrix
key_actors_mul[1:15, ]
```

```{r}
# 위의 top3 배우의 행렬을 이용하여 네트워크 객체를 생성
# 비대칭형 네트워크인 경우, matrix.type = "bipartite"를 추가해주어야 함
net_key_actors <- network(x = key_actors_mul, 
                          directed = FALSE, 
                          matrix.type = "bipartite")
summary(net_key_actors)
```

```{r}
# 각 노드별 중개중심성(betweenness centrality) 계산
key_btwn_centrl <- sna::betweenness(net_key_actors)

# 각 노드별 연결중심성(degree centrality) 계산
key_degree_centrl <- sna::degree(net_key_actors)
```

```{r}
# 노드 컬러 지정 위해 상위 2프로 기준 확인
key_quant98 <- quantile(key_btwn_centrl, probs = 0.98)
key_quant98 # 2016.691
```

```{r}
# 노드 컬러 지정
net_key_actors %v% 'color' <- ifelse(key_btwn_centrl > key_quant98, 'star', 'normal')
key_node_colors <- c('star' = 'gold',
                     'normal' = 'gray80')
```

```{r}
# top 3의 네트워크 맵 그리기
ggnet2(
    # 네트워크 객체 할당 
    net = net_key_actors,
    # 겹치는 노드를 흩어지게 처리
    layout.par = list(cell.jitter = 0.8),
    
    # 노드에 레이블 출력 여부 설정
    label = TRUE,
    # 레이블의 폰트 사이즈 설정
    label.size = 3,
    # 레이블의 컬러 설정
    label.color = 'gray30',
    
    # 노드의 색상을 구분하는 기준. 위에서 만든 'color'를 사용
    # 'color' 대신에 'white'처럼 전체 노드에 대해 하나의 색상으로 지정 가능
    node.color = 'color',
    # 노드의 색상 팔레트
    palette = key_node_colors,
    # 노드의 크기를 연결중심성(degree centrality)에 비례하도록 설정
    node.size = 'degree', # 그냥 이렇게만 쓰면???
    # 엣지의 두께는 특정 숫자로 고정
    edge.size = 0.1,
    
    # 범례 위치 지정. 이번 예제에서는 범례를 출력하지 않도록 설정
    legend.position = 'None',
    # 네트워크 모양 설정 
    # 'circle','kamadakawai','fruchtermanreingold','circrand'
    mode = 'fruchtermanreingold',
    # 글자 폰트 지정
    family = 'NanumGothic')
```
#### 짠! (...)
다른 패키지도 한번 찾아보기로 함..

## 시각화 2 & 3
networkD3 패키지의 simpleNetwork와 forceNetwork 함수를 사용해 시각화 시도.  
코드는 정리해 올릴 예정.  
아래는 forceNetwork를 이용한 시각화 결과물 중 하나.  
```{r, message=FALSE}
rm(list=ls())
library(networkD3)
```

```{r}
load('vis2_random30.RData')
```

```{r}
# 색은 group을 중개중심성(betweenness) 순으로 10그룹으로 나누어 나타냄
# 선 두께 및 선 길이는 같이 작품한 횟수(value) 반영
# node 사이즈는 연결중심성(degree)이 클수록 커지게
forceNetwork(Links = links_df, Nodes = nodes_df,
             Source = "source", Target = "target",
             Value = "value", NodeID = "name", 
             Nodesize = "size", Group = "group",
             height = 1600, width = 1600,
             linkDistance = JS("function(d){return Math.sqrt(d.value) * 10}"), # 제곱했으므로 다시 제곱근으로
             colourScale = JS(
               "d3.scaleOrdinal().domain([1,2,3,4,5,6,7,8,9,10]).range(['#d53e4f', '#f46d43', '#fdae61', '#fee08b', '#ffffbf', '#e6f598', '#abdda4', '#66c2a5', '#3288bd', '#5e4fa2']);"
               ),
             # colourScale = JS(
             #   "d3.scaleOrdinal().domain([1,2,3,4,5,6,7,8,9,10]).range(['#fd8d3c', '#feb24c', '#fed976', '#ffeda0', '#ffffcc', '#ffffe5', '#f7fcb9', '#d9f0a3', '#addd8e', '#78c679']);"
             #   ),
             # colourScale = JS(
             #   "d3.scaleOrdinal().domain([1,2,3,4,5,6,7,8,9,10]).range(['#f768a1', '#fa9fb5', '#fcc5c0', '#fde0dd', '#fff7f3', '#f7fcf0', '#e0f3db', '#ccebc5', '#a8ddb5', '#7bccc4']);"
             #   ),
             fontFamily = "sans-serif", fontSize = 16,
             linkColour = "#EEE", opacity = 1, 
             bounded = F, zoom = F, legend = T, opacityNoHover = 1)
```
#### edge bundling 하는 방법을 찾아 더 깔끔하게 만들던가 좀 더 연구 필요.
D3 구현도 해보기  

### To be continued...
